
# Modelo multinomial logit

```{r}
load('datos_salud_modelo.RData')
```

## Comparación trayectorias

```{r}

with(elsoc_salud_modelo, rcompanion::cramerV(trayectoria_om4.4, trayectoria_gmm.4lin, bias.correct = TRUE))
with(elsoc_salud_modelo, rcompanion::cramerV(trayectoria_om4.4, trayectoria_gmm.5lin, bias.correct = TRUE))

with(elsoc_salud_modelo, rcompanion::cramerV(trayectoria_om4.5, trayectoria_gmm.4lin, bias.correct = TRUE))
with(elsoc_salud_modelo, rcompanion::cramerV(trayectoria_om4.5, trayectoria_gmm.5lin, bias.correct = TRUE))

```


## Variable dependiente: Trayectorias OM 4 clases


```{r}

m1 <- elsoc_salud_modelo %>%
  multinom(trayectoria_om4.4 ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica,
           data = ., weights = ponderador02_w01) 

m2 <- elsoc_salud_modelo %>%
  multinom(trayectoria_om4.4 ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica + fuma_w01 + imc_w01 + proyecto_vida + apoyo_social_w01,
           data = ., weights = ponderador02_w01) 

m3 <- elsoc_salud_modelo %>%
  multinom(trayectoria_om4.4 ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica + fuma_w01 + imc_w01 + proyecto_vida + apoyo_social_w01 + extraversion + agreeableness + conscientiousness + neuroticism + openness,
           data = ., weights = ponderador02_w01) 

modelsummary::modelsummary(list(m1, m2, m3),
                           estimate = "{estimate}{stars}",
                           statistic = NULL,
                           stars = c('*' = .05, '**' = .01, '***' = .001),
                           shape = term + response ~ model,
                           exponentiate = TRUE)


```

## Variable dependiente: Trayectorias OM 5 clases


```{r}

m1 <- elsoc_salud_modelo %>%
  multinom(trayectoria_om4.5 ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica,
           data = ., weights = ponderador02_w01) 

m2 <- elsoc_salud_modelo %>%
  multinom(trayectoria_om4.5 ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica + fuma_w01 + imc_w01 + proyecto_vida + apoyo_social_w01,
           data = ., weights = ponderador02_w01) 

m3 <- elsoc_salud_modelo %>%
  multinom(trayectoria_om4.5 ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica + fuma_w01 + imc_w01 + proyecto_vida + apoyo_social_w01 + extraversion + agreeableness + conscientiousness + neuroticism + openness,
           data = ., weights = ponderador02_w01) 

modelsummary::modelsummary(list(m1, m2, m3),
                           estimate = "{estimate}{stars}",
                           statistic = NULL,
                           stars = c('*' = .05, '**' = .01, '***' = .001),
                           shape = term + response ~ model,
                           exponentiate = TRUE)

```

## Variable dependiente: Trayectorias LCMM 4 clases


```{r}

m1 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.4lin ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica,
           data = ., weights = ponderador02_w01) 

m2 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.4lin ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica + fuma_w01 + imc_w01 + proyecto_vida + apoyo_social_w01,
           data = ., weights = ponderador02_w01) 

m3 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.4lin ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica + fuma_w01 + imc_w01 + proyecto_vida + apoyo_social_w01 + extraversion + agreeableness + conscientiousness + neuroticism + openness,
           data = ., weights = ponderador02_w01) 

modelsummary::modelsummary(list(m1, m2, m3),
                           estimate = "{estimate}{stars}",
                           statistic = NULL,
                           stars = c('*' = .05, '**' = .01, '***' = .001),
                           shape = term + response ~ model,
                           exponentiate = TRUE)

```


## Variable dependiente: Trayectorias LCMM 5 clases


```{r}

m1 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.5lin ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica,
           data = ., weights = ponderador02_w01) 

m2 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.5lin ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica + fuma_w01 + imc_w01 + proyecto_vida + apoyo_social_w01,
           data = ., weights = ponderador02_w01) 

m3 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.5lin ~ m0_sexo_w01 + m0_edad_w01 + log_ing + trayectoria_deuda + trayectoria_apoyo_social + trayectoria_ocup2 + trayectoria_activ_fisica + fuma_w01 + imc_w01 + proyecto_vida + apoyo_social_w01 + extraversion + agreeableness + conscientiousness + neuroticism + openness,
           data = ., weights = ponderador02_w01) 

modelsummary::modelsummary(list(m1, m2, m3),
                           estimate = "{estimate}{stars}",
                           statistic = NULL,
                           stars = c('*' = .05, '**' = .01, '***' = .001),
                           shape = term + response ~ model,
                           exponentiate = TRUE)

```

# Modelo preferido: Trayectorias LCMM con 4 clases (agrupando trayectorias bajas y medias)


```{r}

elsoc_salud_modelo$trayectoria_gmm.5agrup <- factor(car::recode(elsoc_salud_modelo$trayectoria_gmm.5lin, 
                                                                "'Trayectoria baja' = 1; 
                                                                'Trayectoria media' = 1; 
                                                                'Trayectoria remision' = 2; 
                                                                'Trayectoria ascendente' = 3;
                                                                'Trayectoria persistentes' = 4"),
                                                    levels = 1:4,
                                                    labels = c('Trayectoria síntomas bajos/medios', 
                                                               'Trayectoria síntomas moderados decrecientes',
                                                               'Trayectoria síntomas moderados crecientes', 
                                                               'Trayectoria síntomas moderados/severos persistentes'))

mp1 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.5agrup ~ m0_sexo_w01 + m0_edad_w01 + trayectoria_deuda + trayectoria_ocup2,
           data = ., weights = ponderador02_w01) 

mp2 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.5agrup ~ m0_sexo_w01 + m0_edad_w01 + trayectoria_deuda + trayectoria_ocup2 + trayectoria_apoyo_social + trayectoria_activ_fisica + proyecto_vida,
           data = ., weights = ponderador02_w01) 

mp3 <- elsoc_salud_modelo %>%
  multinom(trayectoria_gmm.5agrup ~ m0_sexo_w01 + m0_edad_w01 + trayectoria_deuda + trayectoria_ocup2 + trayectoria_activ_fisica + trayectoria_apoyo_social + proyecto_vida + extraversion + agreeableness + conscientiousness + neuroticism + openness,
           data = ., weights = ponderador02_w01) 

modelsummary::modelsummary(list(mp1, mp2, mp3),
                           estimate = "{estimate}{stars}",
                           statistic = NULL,
                           stars = c('*' = .05, '**' = .01, '***' = .001),
                           shape = term + response ~ model,
                           exponentiate = TRUE)


```

