--- 
title: "Trayectorias de sintomatología depresiva"
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
linkcolor: blue
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
fontsize: 12pt
linestretch: 1.5
toc-depth: 1
lof: True
lot: True
author: Álvaro Jiménez, Fabián Duarte, Edgardo Cerda
description: "Trayectorias de sintomatología depresiva"
github-repo: "edgardo-cerda/trayectorias-salud-mental"
always_allow_html: true
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache=TRUE)

```

# Cargar y preparar datos ELSOC {-}

<div style="text-align: justify">

## Cargar librerías

```{r, warning=FALSE, message=FALSE}
# Librerías básicas
library(tidyverse)
library(sjlabelled)

# Librerias análisis de secuencia
library(TraMineR)
library(TraMineRextras)
library(WeightedCluster)
library(cluster)

# Librería ELSOC
library(elsoc)

# Librerias graficos
library(ggpubr)
library(ggsankey)

# Libreria analisis estadístico
library(nnet)
library(modelsummary)
library(lcmm)

```


```{r}

# Cargar datos ELSOC:
elsoc::load_elsoc(data = 'wide')

# Crear variables de sintomatología depresiva por ola:
elsoc_salud <- elsoc_wide_2016_2021 %>% 
  
  # Se conservan observaciones presentes en las 5 olas
  filter(tipo_atricion == 1) %>% 
  
  # Crear variables de PHQ9
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9_w01 = (s11_01_w01 + s11_02_w01 + s11_03_w01 + s11_04_w01 + s11_05_w01 + s11_06_w01 + s11_07_w01 + s11_08_w01 + s11_09_w01),
         phq9_w02 = (s11_01_w02 + s11_02_w02 + s11_03_w02 + s11_04_w02 + s11_05_w02 + s11_06_w02 + s11_07_w02 + s11_08_w02 + s11_09_w02),
         phq9_w03 = (s11_01_w03 + s11_02_w03 + s11_03_w03 + s11_04_w03 + s11_05_w03 + s11_06_w03 + s11_07_w03 + s11_08_w03 + s11_09_w03),
         phq9_w04 = (s11_01_w04 + s11_02_w04 + s11_03_w04 + s11_04_w04 + s11_05_w04 + s11_06_w04 + s11_07_w04 + s11_08_w04 + s11_09_w04),
         phq9_w05 = (s11_01_w05 + s11_02_w05 + s11_03_w05 + s11_04_w05 + s11_05_w05 + s11_06_w05 + s11_07_w05 + s11_08_w05 + s11_09_w05)) %>% 
  
  # Quitar NAs
  filter(!is.na(phq9_w01), !is.na(phq9_w02), !is.na(phq9_w03), !is.na(phq9_w04), !is.na(phq9_w05)) %>% 
  
  # Crear indicador de depresión en 4 y en 2 categorías:
  mutate(depr4_w01 = car::recode(phq9_w01, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
         depr4_w02 = car::recode(phq9_w02, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
         depr4_w03 = car::recode(phq9_w03, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
         depr4_w04 = car::recode(phq9_w04, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
         depr4_w05 = car::recode(phq9_w05, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"),
         depr2_w01 = car::recode(phq9_w01, "0:9 = 0; 10:27 = 1"), 
         depr2_w02 = car::recode(phq9_w02, "0:9 = 0; 10:27 = 1"), 
         depr2_w03 = car::recode(phq9_w03, "0:9 = 0; 10:27 = 1"),  
         depr2_w04 = car::recode(phq9_w04, "0:9 = 0; 10:27 = 1"), 
         depr2_w05 = car::recode(phq9_w05, "0:9 = 0; 10:27 = 1"),
         phq_sum = depr4_w01 + depr4_w02 + depr4_w03 + depr4_w04 + depr4_w05
         )


# Cargar datos ELSOC LONG:
elsoc::load_elsoc(data = 'long')

# Crear variables de sintomatología depresiva por ola LONG:
elsoc_salud_long <- elsoc_long_2016_2021 %>% 
  
  # Se conservan observaciones presentes en las 5 olas
  filter(tipo_atricion == 1) %>% 
  
  # Crear variables de PHQ9
  purrr::map_at(.at = vars(starts_with('s11_0')), 
                .f = function(s) car::recode(s, "1 = 0; 2 = 1; 3 = 2; c(4, 5) = 3; c(-888, -999) = NA")) %>%
  as.data.frame() %>%  
  mutate(phq9 = (s11_01 + s11_02 + s11_03 + s11_04 + s11_05 + s11_06 + s11_07 + s11_08 + s11_09)) %>% 
  
  # Quitar NAs
  filter(!is.na(phq9)) %>% 
  
  # Crear indicador de depresión en 4 y en 2 categorías:
  mutate(depr4 = car::recode(phq9, "0:4 = 1; 5:9 = 2; 10:14 = 3; 15:27 = 4"), 
         depr2 = car::recode(phq9, "0:9 = 0; 10:27 = 1"))


```
